name: Run Scrapy

name: BuildDockerfileImage

on:
  # 防止 Fork 乱用 actions 设置只能手动触发构建
  workflow_dispatch:
  repository_dispatch:
    types: Run_Scrapy
# on:
#   push:
#     branches: [ main ]
#   pull_request:
#     branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        sudo apt update && sudo apt install wget
        
    - name: Create save folder
      run: mkdir ${{ github.workspace }}/save
      
    - name: Run with script
      run: python scrapy.py
      
    - name: '提交 Git'
      run: |
          git config --global user.email action@github.com
          git config --global user.name GitHub Action
          git add ${{ github.workspace }}/save
          time=$(date "+%Y-%m-%d %H:%M:%S")
          git commit -m "${time} 自动更新" -a
        
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          
#     - name: Tar files
#       run: tar -zcvf BlackHat-PDF.tar.gz -C ${{ github.workspace }} save/

#     - name: Deliver pdf file
#       uses: actions/upload-artifact@v2
#       with:
#         name: BlackHat-PDF
#         path: BlackHat-PDF.tar.gz
